name: 问题汇报
description: 出 bug 啦
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        **在提 issue 前请确保你仔细阅读过 wiki，尤其是“常见问题”部分**，并确保你使用的是最新版的 cq-picsearcher-bot

        在启动本项目出现错误时，你可以无视堆栈 (stack) 相关的信息，但错误信息 (Error: xxxxx) 请认真看看，大部分问题你都可以在本项目 wiki 或搜索引擎中找到解答

        **这些 issue 不会被受理：**

        1. Wiki 中，特别是“常见问题”中有提到的，“已知无法解决的问题”或“有提供解决方案的问题”
        2. 大部分“连接失败”问题，请自己排查配置等原因
  - type: textarea
    attributes:
      label: Bug 描述
      description: 是否稳定复现，是的话说明步骤；期望的正常行为是怎么样的；截图等附件可提交在此处
    validations:
      required: true
  - type: textarea
    attributes:
      label: 日志
      description: 如有相关日志直接可在此提供，无需手动输入 markdown 代码块
      render: shell
  - type: input
    attributes:
      label: 系统及版本
      description: win / mac / linux
  - type: input
    attributes:
      label: Node.js 版本
  - type: input
    attributes:
      label: cq-picsearcher-bot 版本
      description: 查看 package.json 中的 version 字段，或向机器人发送 --version
